### ISSUE TITLE
Small error in Example

### ISSUE THREAD

**Issue by eltonnobrega** [AppLovin/AppLovin-MAX-Cordova#10]
Hi, how are you?
While making the addon for construct 3 I found a small error in the example code:
All occurrences of addEventListener onMRecAd... should start in uppercase: OnMRecAd...

Example:
window.addEventListener('onMRecAdLoadedEvent'
Must be changed to:
window.addEventListener('OnMRecAdLoadedEvent'

**Comment by thomasmso** [comment]
Appreciate it @eltonnobrega, I've fixed it in the latest commit.
