### ISSUE TITLE
Error when adding plugin on iOS

### ISSUE THREAD

**Issue by Carlosps** [AppLovin/AppLovin-MAX-Cordova#12]
When I try to add the plugin on iOS I get the error message. `Installing "cordova-plugin-applovin-max" for ios
(node:36452) [DEP0128] DeprecationWarning: Invalid 'main' field in node_modules/objectorarray/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)`

**Comment by thomasmso** [comment]
This seems to be a warning that derives from the `objecttoarray` package: https://github.com/indentjs/objectorarray/issues/7, you can also use `node --trace-deprecation` as suggested in the log to trace down the exact library owner.

**Comment by Carlosps** [comment]
Thank you @thomasmso. It was indeed an issue with the other package you mentioned.

I have faced another issue when adding this plugin on iOS. I have created a pull request explaining the issue and fixing it, please take a look.

**Comment by thomasmso** [comment]
Hey @Carlosps - checked out the PR and responded to it, lmk if you have any other Qs, and thanks once again for raising that PR!
