### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by tuzke** [AppLovin/AppLovin-MAX-Cordova#17]
When I add implementation 'com.applovin.mediation:google-adapter:+' to build.gradle the build gives error:
```
Execution failed for task ':CordovaLib:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
When deleting it, the build is still successful
Does anyone know how to fix it?

**Comment by thomasmso** [comment]
Could you try updating your build.gradle according to the requirements set forth here and seeing if it works? 
https://developers.google.com/admob/android/quick-start
