### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Carlosps** [AppLovin/AppLovin-MAX-Cordova#20]
I have not changed anything on my code, but now I am getting this error when I try to build the app.
I was able to build the same app two day ago withou any issues.

Any idea what might be causing this issue?

> Task :app:checkDebugDuplicateClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.android.gms.internal.measurement.zzbu found in modules jetified-play-services-measurement-18.0.3-runtime.jar (com.google.android.gms:play-services-measurement:18.0.3) and jetified-play-services-measurement-sdk-api-20.1.2-runtime.jar (com.google.android.gms:play-services-measurement-sdk-api:20.1.2)

**Comment by thomasmso** [comment]
Glad that version works. It might be conflicting transitive dependencies with the 21.0.0 version of AdMob SDK and another Google-owned SDK you have in your project. 

We'll post updates if we hear / find more info relating this from our partners.

**Comment by Carlosps** [comment]
Hi @thomasmso.

Any idea why I am facing this issue when trying to add Pangle ad network as mediation?
It works fine for others ad networks like Admob and Meta.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.pangle.global:ads-sdk:4.5.0.6.
     Required by:
         project :app > com.applovin.mediation:bytedance-adapter:4.5.0.6.0

**Comment by thomasmso** [comment]
Unfortunately, I'm not sure. I havn't seen this issue before. It's worth integrating their SDK independently to see if the issue persists, to isolate the cause from the adapter.
