### ISSUE TITLE
 please make an example ConsentDialogState

### ISSUE THREAD

**Issue by EMI-INDO** [AppLovin/AppLovin-MAX-Cordova#22]
**all ads are showing**

I have made it like this but there is no response in console.log

https://dash.applovin.com/documentation/mediation/cordova/getting-started/privacy

`AppLovinMAX.initialize(YOUR_SDK_KEY, (configuration) => {
    if (configuration.consentDialogState == AppLovinMAX.ConsentDialogState.APPLIES)
    {
        // Show user consent dialog
        console.log(configuration);
    }
    else if (configuration.consentDialogState == AppLovinMAX.ConsentDialogState.DOES_NOT_APPLY)
    {
        // No need to show consent dialog, proceed with initialization
        console.log(configuration);
    }
    else
    {
        // Consent dialog state is unknown. Proceed with initialization, but check if the consent
        // dialog should be shown on the next application initialization
           console.log(configuration);
    }
});`

**Comment by thomasmso** [comment]
Hi @EMI-INDO - Unfortunately we cannot assist with this, our product team has decided that this API will be deprecated and removed in an upcoming plugin release.
