### ISSUE TITLE
problems uploading the apk to google play

### ISSUE THREAD

**Issue by jE-KI** [AppLovin/AppLovin-MAX-Cordova#23]
@thomasmso 

mistake
Your app includes a non-compliant version of the SDK
Version code 45 of your com.xxx.xxx app contains the `com.unity3d.ads:unity-ads` SDK or an SDK that one of your libraries depends on and that collects personal or sensitive data, including but not limited to IDs advertising, Android ID. Persistent device identifiers cannot be linked to personal or sensitive user data or other device identifiers that can be changed, as described in the User Data policy.

As of September 15, 2022 00:00 UTC, new versions of the app that contain SDK versions that do not comply with the User Data policy may be blocked from being released. We recommend that you update the SDK to a policy-compliant version that does not contain the offending code, if your SDK vendor offers that option, or remove the SDK from your application.

Based on the information provided by your SDK vendor, we recommend that you update to `4.0.1.` Contact the SDK vendor for more information.

REQUIRED ACTION: Upload a new version that complies with the policy AND disable the version that does not comply.

Read the User Data policy for more details. See how to submit an updated application for review here.

If you have reviewed the policy and believe we made this decision in error, please contact our Policy Support team.

More information...

**Any idea?**

<img width="921" alt="Screen Shot 2022-07-16 at 18 05 01" src="https://user-images.githubusercontent.com/108358802/179373141-9b0514fa-2fdd-455f-8c96-f6eabfa8feab.png">

**Comment by thomasmso** [comment]
Please update to the latest UnityAds adapter, and you should be fine.

**Comment by EMI-INDO** [comment]
where can i update the adapter?

**Comment by jE-KI** [comment]
where can i update the adapter?

**Comment by thomasmso** [comment]
The warning is for UnityAds' SDK - so you have that in your project somehow. If you never installed via our [docs](https://dash.applovin.com/documentation/mediation/cordova/mediation-adapters/android?network=UNITY_NETWORK)

**Comment by jE-KI** [comment]
Thank you friend.
I will try it.
