### ISSUE TITLE
App Open Ads Format

### ISSUE THREAD

**Issue by Carlosps** [AppLovin/AppLovin-MAX-Cordova#28]
### Feature Description

Any idea when the App Open Ads format will be available on Cordova?

Thank you.

**Comment by thomasmso** [comment]
We currently do not have plans to add the ad format to Cordova. But we can use this GitHub issue to pool requests for us to do so.

**Comment by Carlosps** [comment]
Ok, thank you.

Yeah, it would be great to also have this ad format. Specially because the App Open Ads are growing and becoming more and more relevant in ad revenue.

This feature would make applovin mediation platform more competitive compared to others. As Admob already have it, people could be inclined to be using admob as mediation instead.

Please keep us posted once you have any update, thank you again. Congrats for the great work.

**Comment by Carlosps** [comment]
Hello @thomasmso,

Any updates on that?

**Comment by thomasmso** [comment]
Hi @Carlosps - we don't have enough demand to justify the addition. Since our plugin is open source, you are more than welcome to use our interstitial code as inspiration to build out the App Open functionality in the meantime.
