### ISSUE TITLE
Interstitial showing black screen 

### ISSUE THREAD

**Issue by mohamadorra** [AppLovin/AppLovin-MAX-Cordova#31]
### MAX Plugin Version

Current 

### Cordova Version

Current 

### Device/Platform Info

Pixel 6pro

### Current Behavior

Inter shwoing black screen 

### How to Reproduce

Please fix it

**Comment by thomasmso** [comment]
If it is reproducible, could you share the ad info with us via our [Creative Debugger](https://dash.applovin.com/documentation/mediation/cordova/testing-networks/creative-debugger) tool?
