### ISSUE TITLE
Is it compatible with Capacitor JS?

### ISSUE THREAD

**Issue by Saqib92** [AppLovin/AppLovin-MAX-Cordova#32]
### Feature Description

I need Capacitor js support for this plugin.

**Comment by thomasmso** [comment]
While we cannot prioritize this work atm, we can leave this issue open in case other developers are interested.

**Comment by khang-nd** [comment]
@Saqib92 You can use [this wrapper](https://danielsogl.gitbook.io/awesome-cordova-plugins/applovin). It provides a TypeScript support for this cordova package while making it compatible with Capacitor as well.

**Comment by ZionStage** [comment]
Hey @Pimeko 

Could you provide a more detailed example of how you implemented it using Capacitor please ? I also stumbled onto the procedure but they are using `Angular` and I can't manage to make it work with `React`. It seems like I have a bad configuration.

Thanks !

**Comment by Pimeko** [comment]
Hey @ZionStage 
I'm using VueJS but I can tell you what I've done, if that can help!

I've added these dependencies in my package.json (can't remember which one was useful):
```JSON
"dependencies": {
  "@awesome-cordova-plugins/applovin": "^6.3.0",
  "cordova-plugin-applovin-max": "^1.1.5"
}
```
Then in a basic JS file, I've retrieved the plugin using ```this.AppLovinMAX = window.applovin```, then to be used like 
```
this.AppLovinMAX.setVerboseLogging(true);
this.AppLovinMAX.initialize(...)
```
