### ISSUE TITLE
Load event counts as an impression

### ISSUE THREAD

**Issue by UzverNumber47** [AppLovin/AppLovin-MAX-Cordova#38]
### MAX Plugin Version

1.1.0

### Cordova Version

11.1.0

### Device/Platform Info

Android

### Current Behavior

Every time I get OnBannerAdLoadedEvent it counts as an impression in Mediation Performance Reporting. The same happens with MREC. I thought an impression should count on AppLovinMAX.showBanner()/showMRec(). Not sure if it is a bug or not. Correct me if I'm wrong, please

### Expected Behavior

Impression should count only after calling AppLovinMAX.showBanner()/showMRec()

### How to Reproduce

 window.addEventListener('OnMRecAdLoadedEvent', (adInfo) => {
        this.ga.trackEvent('ads', 'mrec-load-success')
 });

window.addEventListener('OnBannerAdLoadedEvent', (adInfo) => {
        this.ga.trackEvent('ads', 'banner-load-success')
})

amount of impressions in MAX Performance Reporting exactly matches the sum of google analytics mrec-load-success and banner-load-success. In my case it was 117+114 vs 18 times 'show' methods called.

**Comment by applovinAsh** [comment]
Hi [UzverNumber47](https://github.com/UzverNumber47), we are taking a look

**Comment by UzverNumber47** [comment]
After removing the plugin the blank screen issue was gone.

**Comment by applovinAsh** [comment]
For banner ads and MRECs, we log an impression when the ad is rendered as you should load and immediately show the ad for the best results. 

Can you explain more about the banner ad on half of the screen? Can you provide screenshots?

When you get the black screen issue, has an ad been clicked? Do you have any other ad format in your application?

**Comment by UzverNumber47** [comment]
> For banner ads and MRECs, we log an impression when the ad is rendered as you should load and immediately show the ad for the best results.

In my case, mrec takes around 15 seconds to load. I can't show ad at a random place in my app. I need to wait for a proper moment. Maybe banner will work this way if one adds it to the entire application. But I wanted to show banners only on some 
screens.

> Can you explain more about the banner ad on half of the screen? Can you provide screenshots?
Unfortunately no. I got a bad review and that's it. Usually, people don't respond back when they give 1 star with a comment.

> When you get the black screen issue, has an ad been clicked? Do you have any other ad format in your application?
No, the app won't load at all. BTW on both ios and android. 2 android users reported and 1 ios user. After removing the plugin and all dependencies everything started to work as usual.

**Comment by applovinAsh** [comment]
We are unable to reproduce the issue, and without proper logs or a sample application, we cannot troubleshoot further. If the issue happens again, please get the verbose logs and provide them so we can take the proper steps to solve them.
