### ISSUE TITLE
Banner Ad on top of content

### ISSUE THREAD

**Issue by yohan-pannet-bbo** [AppLovin/AppLovin-MAX-Cordova#42]
### Feature Description

Hi,

Currently, when displaying a banner (TOP or BOTTOM), the ad banner is displayed 'above' the page content.

with banner
<img width="392" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Cordova/assets/51915925/4abd7fcb-7fc8-442f-a665-03028466a65f">

without banner
<img width="402" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Cordova/assets/51915925/6d89b197-a3d5-4ae2-8c4a-2cbc741af8bb">

### Feature Description
An option in createBanner so that the banner is displayed 'on top' or 'after' the page content. Without overlapping the content. 
This would work only with TOP & BOTTOM position, not with CENTER one of course.

Is this feature already considered?

**Comment by applovinAsh** [comment]
Hi @yohan-pannet-bbo, thank you for the suggestion. We follow the industry standard on banner size, format, and location. We will consider this suggestion for a future release when we have engineering resources available.

**Comment by applovinAsh** [comment]
Hi @yohan-pannet-bbo, thank you for the suggestion. We follow the industry standard on banner size, format, and location. We will consider this suggestion for a future release when we have engineering resources available.
