### ISSUE TITLE
100% CPU usage after app is paused

### ISSUE THREAD

**Issue by DashiellP** [AppLovin/AppLovin-MAX-Cordova#44]
### MAX Plugin Version

1.1.2

### Cordova Version

12.0.0

### Device/Platform Info

Android

### Current Behavior

When the app is paused (either by being minimized or viewing an ad) the framerate drops to < 10 and the CPU usage goes up to 100%. The Chrome inspector shows that the lag is caused by these huge paint events.

![image](https://github.com/AppLovin/AppLovin-MAX-Cordova/assets/22898715/d470f999-dcde-464f-959b-11ff357c3e85)

The lag can be prevented by not initializing the AppLovin SDK or by disabling all third-party ad network SDK's. It persists until the app is restarted (refreshing in the inspector does not fix it). There are no errors in logcat or the JS console.

### How to Reproduce

- Launch the app
- Initialize the SDK
- Go to the home screen
- Return to the app

**Comment by thomasmso** [comment]
Thanks for raising this issue @DashiellP. If you de-integrate all adapters, leaving you with AppLovin ads only - is it still reproducible? Consistently?

When FPS drops while viewing an ad, is the ad UX fine or is it lagging/stuttering as well?

**Comment by DashiellP** [comment]
De-integrating all other adapters does solve it, but including even one other adapter reintroduces the problem. 

The ad video FPS seems fine, but the FPS drop in-app is consistent.

**Comment by thomasmso** [comment]
Would you be able to provide an APK with all adapters de-integrated, and one with it integrated? I want to reproduce this issue locally.

We can work closer together if you email me at thomas.so@applovin.com.

**Comment by thomasmso** [comment]
@DashiellP - Could you try the latest Cordova plugin? v1.1.4.
