### ISSUE TITLE
[12.0.0+] Support for TCF v2 Compliance and Google UMP

### ISSUE THREAD

**Issue by Chadori** [AppLovin/AppLovin-MAX-Cordova#47]
### Feature Description

Hi there,

It's an urgent request from a client's publisher. Would you be exposing the API for Android SDK and iOS SDK versions 12.0.0+, which includes TCF v2 Compliance and Google UMP?

Would it be possible to know if you are planning to support the new API and when? Since our client needs it before mid-January.

I hope you can give us information promptly so that we can have time to write one ourselves if not.

Thank you.

**Comment by thomasmso** [comment]
@Chadori - We currently do not have any plans to bring our Google UMP Automation ([Android docs](https://dash.applovin.com/documentation/mediation/android/getting-started/terms-and-privacy-policy-flow#google-ump-automation) | [iOS docs](https://dash.applovin.com/documentation/mediation/ios/getting-started/terms-and-privacy-policy-flow#google-ump-automation)) feature to Cordova.

Note that your client can still integrate Google UMP separately. Just make sure to initialize our SDK as well as MMP/analytics SDKs after the consent flow is finished.

Our Google UMP Automation feature is only to ease integration of Google UMP and abstract the complexity behind our product, but it is 100% optional.

**Comment by Chadori** [comment]
Thanks for the info.
