### ISSUE TITLE
Update plugin

### ISSUE THREAD

**Issue by creakosta** [AppLovin/AppLovin-MAX-Cordova#5]
Hello!

I use this plugin for android and want to use in ios, but iOS documentation say that:
"We removed version 10.3.0 because of an issue with initializing the SDK. Please use 10.3.2 instead."

Also I want to know - how to use Consent Flow in cordova? Should I integrate Consent Flow if I use only Applovin network and add SKAdNetwork to Info.plist?

**Comment by thomasmso** [comment]
Hi,

For now, you can follow the docs [here](https://dash.applovin.com/documentation/mediation/ios/getting-started/consent-flow#info.plist) to enable it from the Info.plist file. It's recommended to always use the consent flow to give users a chance to opt into more relevant ad targeting. Thanks!
