### ISSUE TITLE
On iOS, non-AppLovin SDKs cause ANR

### ISSUE THREAD

**Issue by kreso22** [AppLovin/AppLovin-MAX-Cordova#56]
### MAX Plugin Version

12.3.1 & 12.4.1 (either)

### Cordova Version

12.0.0 (cordova-lib@12.0.1), cordova-ios 7.1.1

### Device/Platform Info

iOS 18 / iOS 17.5

### Crashes/ANRs per Day

1/1

### Percentage of Users Affected

1/1

### First Occurrence of Crash/ANR

Last updated 2 months ago, it worked then.
Not sure what changed (iOS version, XCode, Google SDK, Unity SDK..). 

AppLovin SDK version stayed the same. 

### Exception and Stack Trace

`Failed to look up symbolic reference at 0x104c7528f - offset 541705 - symbol symbolic _____Sg ScP in /private/var/containers/Bundle/Application/419544DE-XXXX-XXXX-XXXX-C5A01A1BC0C7/MyApp.app/MyApp`

### How to Reproduce

AppLovin SDK works out of the box. Adding additional SDKs causes ANR.

1) Add AppLovinMediationGoogleAdapter pod to Podfile.
Launch app, notice ANR as soon as the app boots up.

- OR - 

2) Add AppLovinMediationUnityAdsAdapter to Podfile
Launch app, notice ANR within 2-3 seconds after app boots up.

### Reproducible in the demo app?

Not Tested

### Additional Info

<img width="1357" alt="Screenshot 2024-09-28 at 1 52 31 PM" src="https://github.com/user-attachments/assets/6c14d372-a959-45f6-a44b-2dfe8f964833">

**Comment by thomasmso** [comment]
@kreso22 - could you try reproducing this in the demo app and sending the project over?

**Comment by kreso22** [comment]
Tried running the example. I see this error, trying to reference `https://github.com/AppLovin/Public-CocoaPods-Specs/`.
I will change this to `https://github.com/AppLovin/CocoaPods-Specs` and try that.

<img width="760" alt="Screenshot 2024-09-30 at 5 04 56 PM" src="https://github.com/user-attachments/assets/1ac2de2c-5b6b-4755-b2c8-9775e900679e">

**Comment by kreso22** [comment]
I'm not able to build the example for iOS.

I am concerned if I start fixing these errors I will lose the whole point - testing in a predictable environment. Please advise.


<img width="268" alt="Screenshot 2024-09-30 at 5 39 58 PM" src="https://github.com/user-attachments/assets/2636c9ec-b921-43f3-828b-93dd910b27d1">

**Comment by thomasmso** [comment]
If you check out our latest Corova release, it is meant to work with underlying Android and iOS SDK versions 12.3.1: https://github.com/AppLovin/AppLovin-MAX-Cordova/releases

It looks like you are using 13.0.0 which is why you're receiving those build errors. You'd have to hardcode in your CocoaPod `Podfile`s to use SDK version 12.3.1.

**Comment by kreso22** [comment]
I updated to latest applovin-max plugin (1.1.5) and was able to build successfully (Pod 12.3.1 is now included).

Once built, I run the demo app on the device and it hangs.


<img width="1134" alt="Screenshot 2024-09-30 at 8 24 32 PM" src="https://github.com/user-attachments/assets/c0a06b93-ff09-462a-95e6-50cb9f284d1f">

**Comment by kreso22** [comment]
I think I found the solution:

Change `iOS Deployment Target` to `15`.

Both the demo app, and my app build and run successfully now.

**Comment by thomasmso** [comment]
Our SDK's min deployment target is much lower than that, so I suspect it is another artifact in your project requiring it.

**Comment by kreso22** [comment]
I understand, but I don't think so. I suspect perhaps it has to do with Xcode 16 because the demo app didn't work either.
