### ISSUE TITLE
Strange banner behavior on android

### ISSUE THREAD

**Issue by creakosta** [AppLovin/AppLovin-MAX-Cordova#6]
Hi!

I integrated banner on iOS and he work fine, but not on android. Documentation say that "banners are automatically sized to 320x50 on phones and 728x90 on tablets" but on my phone Pixel 4a in landscape mode banner is sized to {screen width}x50 and if I touch the screen he becomes invisible like it go to the behind of view

**Comment by thomasmso** [comment]
Hi, do you have integration code and/or are you able to reproduce this in the demo app in this repo?

**Comment by creakosta** [comment]
> Hi, do you have integration code and/or are you able to reproduce this in the demo app in this repo?

My code is:
```
function LoadBanner(){
AppLovinMAX.createBanner(BANNER_AD_UNIT_ID, AppLovinMAX.AdViewPosition.TOP_CENTER);
AppLovinMAX.setBannerBackgroundColor(BANNER_AD_UNIT_ID, '#ffffff');
}

function ShowBanner(){
AppLovinMAX.showBanner(BANNER_AD_UNIT_ID);
}
```
I also get banner size {screen width}x50 in portrait mode

**Comment by thomasmso** [comment]
We're looking into it.

**Comment by creakosta** [comment]
Hi @thomasmso 
I tested on different devices, it looks like banner automatically sized only on iphone and ipad, but on android the banner is rendered as responsive in any screen orientation. You can see it here:
![Ed1h_b5T9g0](https://user-images.githubusercontent.com/15105267/127483683-2e8c6243-1c1a-4542-abf4-3d2fabc03a37.jpg)
![-vxlHRDVynQ](https://user-images.githubusercontent.com/15105267/127483717-d6fba541-49bc-4186-abc5-4f3d6b009931.jpg)
Can you fix it?

**Comment by thomasmso** [comment]
Hey @creakosta - This is not an issue, we have banner inventory that is sized to the width of the screen or as standard 320 or 728 points. We recommend setting a background color to keep the UX more consistent for the user.
